AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with a public subnet

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.4.0.0/16
      Tags: 
        - Key: Name
          Value: vpc-4

  Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: 10.4.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: sub-4
# This template is fine
