AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with a public subnet

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.3.0.0/16
      Tags: 
        - Key: Name
          Value: MyVPC-jenkins

  Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: 10.3.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MySubnet-jenkins
# This template is fine
